"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from marshmallow import fields
from sdk import utils
from typing import Optional

class CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeEnum(str, Enum):
    r"""The type of checkout key to create. This may be either `deploy-key` or `user-key`."""
    USER_KEY = 'user-key'
    DEPLOY_KEY = 'deploy-key'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateCheckoutKeyCheckoutKeyInput:
    
    type: CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of checkout key to create. This may be either `deploy-key` or `user-key`."""
    

@dataclasses.dataclass
class CreateCheckoutKeyRequest:
    
    project_slug: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project-slug', 'style': 'simple', 'explode': False }})
    r"""Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped."""
    request_body: Optional[CreateCheckoutKeyCheckoutKeyInput] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateCheckoutKeyDefaultApplicationJSON:
    r"""Error response."""
    
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    
class CreateCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum(str, Enum):
    r"""The type of checkout key. This may be either `deploy-key` or `github-user-key`."""
    DEPLOY_KEY = 'deploy-key'
    GITHUB_USER_KEY = 'github-user-key'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateCheckoutKeyCheckoutKey:
    r"""The checkout key."""
    
    created_at: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created-at'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    r"""The date and time the checkout key was created."""
    fingerprint: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('fingerprint') }})
    r"""An SSH key fingerprint."""
    preferred: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('preferred') }})
    r"""A boolean value that indicates if this key is preferred."""
    public_key: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('public-key') }})
    r"""A public SSH key."""
    type: CreateCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of checkout key. This may be either `deploy-key` or `github-user-key`."""
    

@dataclasses.dataclass
class CreateCheckoutKeyResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    checkout_key: Optional[CreateCheckoutKeyCheckoutKey] = dataclasses.field(default=None)
    r"""The checkout key."""
    create_checkout_key_default_application_json_object: Optional[CreateCheckoutKeyDefaultApplicationJSON] = dataclasses.field(default=None)
    r"""Error response."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    