"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclasses.dataclass
class DeleteEnvironmentVariableFromContextRequest:
    
    context_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'context-id', 'style': 'simple', 'explode': False }})
    r"""ID of the context (UUID)"""
    env_var_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'env-var-name', 'style': 'simple', 'explode': False }})
    r"""The name of the environment variable"""
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeleteEnvironmentVariableFromContextDefaultApplicationJSON:
    r"""Error response."""
    
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeleteEnvironmentVariableFromContextMessageResponse:
    r"""message response"""
    
    message: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message') }})
    r"""A human-readable message"""
    

@dataclasses.dataclass
class DeleteEnvironmentVariableFromContextResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_environment_variable_from_context_default_application_json_object: Optional[DeleteEnvironmentVariableFromContextDefaultApplicationJSON] = dataclasses.field(default=None)
    r"""Error response."""
    message_response: Optional[DeleteEnvironmentVariableFromContextMessageResponse] = dataclasses.field(default=None)
    r"""A confirmation message"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    