"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from sdk.models import operations
from typing import Optional

class Schedule:
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    def create_schedule(self, request: operations.CreateScheduleRequest) -> operations.CreateScheduleResponse:
        r"""Create a schedule
        Creates a schedule and returns the created schedule.
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.CreateScheduleRequest, base_url, '/project/{project-slug}/schedule', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        
        client = self._security_client
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.CreateScheduleResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 201:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.CreateScheduleSchedule])
                res.schedule = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.CreateScheduleDefaultApplicationJSON])
                res.create_schedule_default_application_json_object = out

        return res

    def delete_schedule_by_id(self, request: operations.DeleteScheduleByIDRequest) -> operations.DeleteScheduleByIDResponse:
        r"""Delete a schedule
        Deletes the schedule by id.
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.DeleteScheduleByIDRequest, base_url, '/schedule/{schedule-id}', request)
        
        
        client = self._security_client
        
        http_res = client.request('DELETE', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.DeleteScheduleByIDResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteScheduleByIDMessageResponse])
                res.message_response = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.DeleteScheduleByIDDefaultApplicationJSON])
                res.delete_schedule_by_id_default_application_json_object = out

        return res

    def get_schedule_by_id(self, request: operations.GetScheduleByIDRequest) -> operations.GetScheduleByIDResponse:
        r"""Get a schedule
        Get a schedule by id.
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.GetScheduleByIDRequest, base_url, '/schedule/{schedule-id}', request)
        
        
        client = self._security_client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.GetScheduleByIDResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.GetScheduleByIDSchedule])
                res.schedule = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.GetScheduleByIDDefaultApplicationJSON])
                res.get_schedule_by_id_default_application_json_object = out

        return res

    def list_schedules_for_project(self, request: operations.ListSchedulesForProjectRequest) -> operations.ListSchedulesForProjectResponse:
        r"""Get all schedules
        Returns all schedules for this project.
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.ListSchedulesForProjectRequest, base_url, '/project/{project-slug}/schedule', request)
        
        query_params = utils.get_query_params(operations.ListSchedulesForProjectRequest, request)
        
        client = self._security_client
        
        http_res = client.request('GET', url, params=query_params)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListSchedulesForProjectResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.ListSchedulesForProject200ApplicationJSON])
                res.list_schedules_for_project_200_application_json_object = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.ListSchedulesForProjectDefaultApplicationJSON])
                res.list_schedules_for_project_default_application_json_object = out

        return res

    def update_schedule(self, request: operations.UpdateScheduleRequest) -> operations.UpdateScheduleResponse:
        r"""Update a schedule
        Updates a schedule and returns the updated schedule.
        """
        base_url = self._server_url
        
        url = utils.generate_url(operations.UpdateScheduleRequest, base_url, '/schedule/{schedule-id}', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "request_body", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        
        client = self._security_client
        
        http_res = client.request('PATCH', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.UpdateScheduleResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.UpdateScheduleSchedule])
                res.schedule = out
        else:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[operations.UpdateScheduleDefaultApplicationJSON])
                res.update_schedule_default_application_json_object = out

        return res

    